### ISSUE TITLE
What license do you prefer?

### ISSUE THREAD

**Issue by GarrettArm** [summon/summon-api-toolkit#2]
Not having a license limits my ability to borrow from this code.  I'd like to use some of the code.

Could you add an opensource license to the project?  Like MIT or something similar

**Comment by GarrettArm** [comment]
@geofferson @danalicuben @DDoneux  I'm not sure who to address this to.

**Comment by danalicuben** [comment]
Hi @GarrettArm - I added an MIT license to the repo. Thanks!

**Comment by GarrettArm** [comment]
@danalicuben   Thank you so much.  This repo is saving me a lot of time.  I was struggling with how to make the digest value.  After 15 minutes of studying your app, my node app succeeded in getting a response.  Thank you

**Comment by danalicuben** [comment]
Glad to hear it! It can definitely be quite tricky. @DominicDoneux deserves all the credit here.
